/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/passwordLogin': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 密码登录 */
    post: operations['AuthController_passwordLogin']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/phoneLogin': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['AuthController_phoneLogin']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/currentLogin': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['AuthController_currentLogin']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 退出登录 */
    post: operations['AuthController_logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/common/get': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['CommonController_readData']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/common/update': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['CommonController_writeData']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/user': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 分页查询用户列表 */
    get: operations['SystemUserController_pageUser']
    put?: never
    /** 创建用户 */
    post: operations['SystemUserController_createUser']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/user/option': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 分页查询用户列表(可选字段) */
    get: operations['SystemUserController_pageOptionUser']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/user/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 按id查询用户 */
    get: operations['SystemUserController_findUserById']
    /** 修改用户 */
    put: operations['SystemUserController_updateUser']
    post?: never
    /** 删除用户 */
    delete: operations['SystemUserController_removeUser']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/user/batch/query': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 按ids查询用户 */
    post: operations['SystemUserController_findUserListByIds']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/user/batch/delete': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 批量删除用户 */
    post: operations['SystemUserController_batchRemoveUser']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/user/{id}/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 修改用户状态 */
    post: operations['SystemUserController_updateUserStatus']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/user/batch/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 批量修改用户状态 */
    post: operations['SystemUserController_batchUpdateUserStatus']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/user/template': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 下载导入模板 */
    get: operations['SystemUserController_downloadUserTemplate']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/user/import': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 导入数据 */
    post: operations['SystemUserController_importUser']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/user/export': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 导出数据 */
    post: operations['SystemUserController_exportUser']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    ResponseHeadDto: {
      /**
       * @description 错误码，0 代表成功
       * @example 0
       */
      errCode: number
      /**
       * @description 错误信息描述
       * @example success
       */
      errMsg: string
    }
    ApiResponseDto: {
      head: components['schemas']['ResponseHeadDto']
    }
    LoginResponseDto: {
      /**
       * @description 用户ID
       * @example testId
       */
      id: string
      /**
       * @description 用户名
       * @example testName
       */
      userName: string
      /**
       * @description 角色列表
       * @example ["admin"]
       */
      roles: string[]
    }
    PasswordLoginDto: {
      /**
       * @description 登录类型
       * @enum {string}
       */
      type: 'password' | 'phone'
      /** @description 用户名 */
      userName: string
      /** @description 密码 */
      password: string
    }
    PhoneLoginDto: {
      /** @enum {string} */
      type: 'password' | 'phone'
      /** @description 手机号 */
      phone: string
      /** @description 验证码 */
      code: string
    }
    CurrentLoginResponseDto: {
      /**
       * @description 用户ID
       * @example testId
       */
      id: string
      /**
       * @description 用户名
       * @example testName
       */
      userName: string
      /**
       * @description 用户角色列表
       * @example ["admin"]
       */
      roles: string[]
      /**
       * @description 用户权限列表
       * @example ["sys:user:delete"]
       */
      permissions: string[]
    }
    UpdateCommonDto: Record<string, never>
    PaginatedResult: Record<string, never>
    SystemUserPageResp: {
      /**
       * @description 用户ID
       * @example 123
       */
      id: number
      /**
       * @description 用户名
       * @example testName
       */
      userName: string
      /**
       * @description 手机号
       * @example 13511112222
       */
      mobile: string
      /**
       * @description 生日
       * @example 1991-01-01
       */
      birth: string
    }
    SystemUserResp: {
      /**
       * @description 用户ID
       * @example 123
       */
      id: number
      /**
       * @description 用户名
       * @example testName
       */
      userName: string
      /**
       * @description 手机号
       * @example 13511112222
       */
      mobile: string
      /**
       * @description 生日
       * @example 1991-01-01
       */
      birth: string
    }
    BatchDto: Record<string, never>
    SystemUserCreateDto: Record<string, never>
    SystemUserUpdateDto: {
      /**
       * @description 状态，1：启用，0：禁用
       * @example 1
       */
      status: string
    }
    BatchResp: Record<string, never>
    BatchUpdateStatusDto: Record<string, never>
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  AuthController_passwordLogin: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordLoginDto']
      }
    }
    responses: {
      /** @description 成功响应 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponseDto'] & {
            data?: components['schemas']['LoginResponseDto']
          }
        }
      }
    }
  }
  AuthController_phoneLogin: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PhoneLoginDto']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  AuthController_currentLogin: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 成功响应 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponseDto'] & {
            data?: components['schemas']['CurrentLoginResponseDto']
          }
        }
      }
    }
  }
  AuthController_logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 成功响应 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponseDto'] & {
            /** @default null */
            data: null | null
          }
        }
      }
    }
  }
  CommonController_readData: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  CommonController_writeData: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateCommonDto']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  SystemUserController_pageUser: {
    parameters: {
      query: {
        /** @description 用户姓名 */
        userName: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 分页成功响应 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponseDto'] & {
            data?: components['schemas']['PaginatedResult'] & {
              /**
               * @description 总条数
               * @example 100
               */
              total?: number
              /**
               * @description 当前页码
               * @example 1
               */
              page?: number
              /**
               * @description 每页条数
               * @example 10
               */
              pageSize?: number
              list?: components['schemas']['SystemUserPageResp'][]
            }
          }
        }
      }
    }
  }
  SystemUserController_createUser: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SystemUserCreateDto']
      }
    }
    responses: {
      /** @description 成功响应 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponseDto'] & {
            data?: components['schemas']['SystemUserResp']
          }
        }
      }
    }
  }
  SystemUserController_pageOptionUser: {
    parameters: {
      query: {
        /** @description 关键字，可输入姓名，手机号，身份证等 */
        keyword: string
        /** @description 返回的字段，默认是id,username */
        fields?: string[]
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 分页成功响应 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponseDto'] & {
            data?: components['schemas']['PaginatedResult'] & {
              /**
               * @description 总条数
               * @example 100
               */
              total?: number
              /**
               * @description 当前页码
               * @example 1
               */
              page?: number
              /**
               * @description 每页条数
               * @example 10
               */
              pageSize?: number
              list?: components['schemas']['SystemUserPageResp'][]
            }
          }
        }
      }
    }
  }
  SystemUserController_findUserById: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 成功响应 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponseDto'] & {
            data?: components['schemas']['SystemUserResp']
          }
        }
      }
    }
  }
  SystemUserController_updateUser: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SystemUserUpdateDto']
      }
    }
    responses: {
      /** @description 成功响应 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponseDto'] & {
            data?: components['schemas']['SystemUserResp']
          }
        }
      }
    }
  }
  SystemUserController_removeUser: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 成功响应 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponseDto'] & {
            /** @default null */
            data: null | null
          }
        }
      }
    }
  }
  SystemUserController_findUserListByIds: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['BatchDto']
      }
    }
    responses: {
      /** @description 成功响应 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponseDto'] & {
            data?: components['schemas']['SystemUserResp']
          }
        }
      }
    }
  }
  SystemUserController_batchRemoveUser: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['BatchDto']
      }
    }
    responses: {
      /** @description 成功响应 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponseDto'] & {
            data?: components['schemas']['BatchResp']
          }
        }
      }
    }
  }
  SystemUserController_updateUserStatus: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 成功响应 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponseDto'] & {
            /** @default null */
            data: null | null
          }
        }
      }
    }
  }
  SystemUserController_batchUpdateUserStatus: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['BatchUpdateStatusDto']
      }
    }
    responses: {
      /** @description 成功响应 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponseDto'] & {
            data?: components['schemas']['BatchResp']
          }
        }
      }
    }
  }
  SystemUserController_downloadUserTemplate: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 成功响应 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponseDto'] & {
            /** @default null */
            data: null | null
          }
        }
      }
    }
  }
  SystemUserController_importUser: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 成功响应 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponseDto'] & {
            /** @default null */
            data: null | null
          }
        }
      }
    }
  }
  SystemUserController_exportUser: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 成功响应 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponseDto'] & {
            /** @default null */
            data: null | null
          }
        }
      }
    }
  }
}
