/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/passwordLogin': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 密码登录 */
    post: operations['AuthController_passwordLogin']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/phoneLogin': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['AuthController_phoneLogin']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/currentLogin': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['AuthController_currentLogin']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 退出登录 */
    post: operations['AuthController_logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/common/get': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: operations['CommonController_readData']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/common/update': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post: operations['CommonController_writeData']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/user/page': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 分页查询用户列表 */
    get: operations['UserController_pageUser']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/user/schema-generator-holder-page-user': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * 请勿调用，用于生成前端DTO
     * @deprecated
     */
    post: operations['UserController__pageUser']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/user/option': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 分页查询用户列表(可选字段) */
    get: operations['UserController_pageOptionUser']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/user/schema-generator-holder-page-option-user': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * 请勿调用，用于生成前端DTO
     * @deprecated
     */
    post: operations['UserController__pageOptionUser']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/user/find/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 按id查询用户 */
    get: operations['UserController_findUserById']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/user/batch/query': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 按ids查询用户 */
    get: operations['UserController_findUserListByIds']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/user/create': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 创建用户 */
    post: operations['UserController_createUser']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/user/update/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 修改用户 */
    post: operations['UserController_updateUser']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/user/delete/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 删除用户 */
    post: operations['UserController_removeUser']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/user/batch/delete': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 批量删除用户 */
    post: operations['UserController_batchRemoveUser']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/user/updateStatus/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 修改用户状态 */
    post: operations['UserController_updateUserStatus']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/user/batch/status': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 批量修改用户状态 */
    post: operations['UserController_batchUpdateUserStatus']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/user/template': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 下载导入用户模板 */
    post: operations['UserController_downloadUserTemplate']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/user/import': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 导入用户数据 */
    post: operations['UserController_importUser']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/user/export': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 导出用户数据 */
    post: operations['UserController_exportUser']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/user/check-unique': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 检测字段是否唯一 */
    get: operations['UserController_checkUnique']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    ResponseHeadDto: {
      /**
       * @description 错误码，0 代表成功
       * @example 0
       */
      errCode: number
      /**
       * @description 错误信息描述
       * @example success
       */
      errMsg: string
    }
    ApiResponseDto: {
      head: components['schemas']['ResponseHeadDto']
    }
    LoginResponseDto: {
      /**
       * @description 用户ID
       * @example testId
       */
      id: string
      /**
       * @description 用户名
       * @example testName
       */
      userName: string
      /**
       * @description 角色列表
       * @example ["admin"]
       */
      roles: string[]
    }
    PasswordLoginDto: {
      /** @description 用户名 */
      userName: string
      /** @description 密码 */
      password: string
    }
    PhoneLoginDto: {
      /** @description 手机号 */
      phone: string
      /** @description 验证码 */
      code: string
    }
    CurrentLoginResponseDto: {
      /**
       * @description 用户ID
       * @example testId
       */
      id: string
      /**
       * @description 用户名
       * @example testName
       */
      userName: string
      /**
       * @description 用户角色列表
       * @example ["admin"]
       */
      roles: string[]
      /**
       * @description 用户权限列表
       * @example ["sys:user:delete"]
       */
      permissions: string[]
    }
    UpdateCommonDto: Record<string, never>
    PaginatedResult: Record<string, never>
    UserPageRespDto: {
      /** @description 用户id */
      id: number
      /** @description 用户名 */
      userName: string
      /** @description 昵称 */
      nickName?: string
      /** @description 性别代码 */
      gender?: string
      /** @description 性别名称 */
      genderName?: string
      /** @description 生日 */
      birth?: string
      /** @description 手机号 */
      mobile?: string
      /** @description 地址 */
      address?: string
      /** @description 地址详情 */
      addressDetail?: string
      /** @description 婚姻状况代码 */
      maritalStatus?: string
      /** @description 婚姻状况名称 */
      maritalStatusName?: string
      /** @description 邮箱 */
      email?: string
      /** @description 状态：0-禁用，1-启用 */
      status?: string
      /** @description 创建时间 */
      createdAt?: string
      /** @description 修改时间 */
      updatedAt?: string
      /** @description 删除时间 */
      deletedAt?: string
      /** @description 全拼 */
      pinyin?: string
      /** @description 拼音首字母 */
      py?: string
    }
    UserPageDto: {
      /** @description 昵称 */
      nickName?: string
      /** @description 性别代码 */
      gender?: string
      /** @description 性别名称 */
      genderName?: string
      /** @description 生日 */
      birth?: string
      /** @description 手机号 */
      mobile?: string
      /** @description 地址 */
      address?: string
      /** @description 地址详情 */
      addressDetail?: string
      /** @description 婚姻状况代码 */
      maritalStatus?: string
      /** @description 婚姻状况名称 */
      maritalStatusName?: string
      /** @description 邮箱 */
      email?: string
      /** @description 状态：0-禁用，1-启用 */
      status?: string
      /** @description 创建时间 */
      createdAt?: string
      /** @description 修改时间 */
      updatedAt?: string
      /** @description 删除时间 */
      deletedAt?: string
      /** @description 全拼 */
      pinyin?: string
      /** @description 拼音首字母 */
      py?: string
      /** @description 页码 */
      page?: number
      /** @description 每页条数 */
      pageSize?: number
      /** @description 用户名 */
      userName?: string
      /**
       * @description 创建日期开始
       * @example 2000-10-10 00:00:00
       */
      createdAtStart?: string
      /**
       * @description 创建日期结束
       * @example 2000-10-10 23:59:59
       */
      createdAtEnd?: string
      /**
       * @description 开始
       * @example 2000-10-10 00:00:00
       */
      updatedAtStart?: string
      /**
       * @description 结束
       * @example 2000-10-10 23:59:59
       */
      updatedAtEnd?: string
      /**
       * @description 排序对象
       * @example {
       *       "userName": "ASC",
       *       "createdAt": "DESC"
       *     }
       */
      sort?: {
        [key: string]: string
      }
    }
    UserPageOptionDto: {
      /** @description 页码 */
      page?: number
      /** @description 每页条数 */
      pageSize?: number
      /**
       * @description 关键字
       * @example
       */
      keyword?: string
      /**
       * @description 返回的列表字段
       * @example
       */
      fields?: string
    }
    UserRespDto: {
      /** @description 用户id */
      id: number
      /** @description 用户名 */
      userName: string
      /** @description 昵称 */
      nickName?: string
      /** @description 性别代码 */
      gender?: string
      /** @description 性别名称 */
      genderName?: string
      /** @description 生日 */
      birth?: string
      /** @description 手机号 */
      mobile?: string
      /** @description 地址 */
      address?: string
      /** @description 地址详情 */
      addressDetail?: string
      /** @description 婚姻状况代码 */
      maritalStatus?: string
      /** @description 婚姻状况名称 */
      maritalStatusName?: string
      /** @description 邮箱 */
      email?: string
      /** @description 状态：0-禁用，1-启用 */
      status?: string
      /** @description 创建时间 */
      createdAt?: string
      /** @description 修改时间 */
      updatedAt?: string
      /** @description 删除时间 */
      deletedAt?: string
      /** @description 全拼 */
      pinyin?: string
      /** @description 拼音首字母 */
      py?: string
    }
    UserListRespDto: {
      /**
       * @description 未找到的id数组
       * @example
       */
      notFoundIds?: string[]
      /** @description 用户列表 */
      list: string[]
    }
    UserCreateDto: {
      /** @description 昵称 */
      nickName?: string
      /** @description 性别代码 */
      gender?: string
      /** @description 性别名称 */
      genderName?: string
      /** @description 生日 */
      birth?: string
      /** @description 手机号 */
      mobile?: string
      /** @description 地址 */
      address?: string
      /** @description 地址详情 */
      addressDetail?: string
      /** @description 婚姻状况代码 */
      maritalStatus?: string
      /** @description 婚姻状况名称 */
      maritalStatusName?: string
      /** @description 邮箱 */
      email?: string
      /** @description 状态：0-禁用，1-启用 */
      status?: string
      /** @description 创建时间 */
      createdAt?: string
      /** @description 修改时间 */
      updatedAt?: string
      /** @description 删除时间 */
      deletedAt?: string
      /** @description 全拼 */
      pinyin?: string
      /** @description 拼音首字母 */
      py?: string
      /** @description 用户名 */
      userName: string
      /** @description 用户角色 */
      roles?: string[]
    }
    UserUpdateDto: {
      /** @description 昵称 */
      nickName?: string
      /** @description 性别代码 */
      gender?: string
      /** @description 性别名称 */
      genderName?: string
      /** @description 生日 */
      birth?: string
      /** @description 手机号 */
      mobile?: string
      /** @description 地址 */
      address?: string
      /** @description 地址详情 */
      addressDetail?: string
      /** @description 婚姻状况代码 */
      maritalStatus?: string
      /** @description 婚姻状况名称 */
      maritalStatusName?: string
      /** @description 邮箱 */
      email?: string
      /** @description 状态：0-禁用，1-启用 */
      status?: string
      /** @description 创建时间 */
      createdAt?: string
      /** @description 修改时间 */
      updatedAt?: string
      /** @description 删除时间 */
      deletedAt?: string
      /** @description 全拼 */
      pinyin?: string
      /** @description 拼音首字母 */
      py?: string
      /** @description 用户名 */
      userName?: string
      /** @description 用户角色 */
      roles?: string[]
    }
    BatchRespDto: {
      /**
       * @description 未找到的id数组
       * @example
       */
      notFoundIds?: string[]
    }
    BatchDto: {
      /**
       * @description 用“,”拼接的id
       * @example
       */
      ids: string
    }
    UpdateStatusDto: {
      /**
       * @description 状态值
       * @enum {string}
       */
      status: '1' | '0'
    }
    BatchUpdateStatusDto: {
      /**
       * @description 用“,”拼接的id
       * @example
       */
      ids: string
      /**
       * @description 状态
       * @enum {string}
       */
      status: '1' | '0'
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  AuthController_passwordLogin: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordLoginDto']
      }
    }
    responses: {
      /** @description 成功响应 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponseDto'] & {
            data: components['schemas']['LoginResponseDto']
          }
        }
      }
    }
  }
  AuthController_phoneLogin: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PhoneLoginDto']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  AuthController_currentLogin: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 成功响应 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponseDto'] & {
            data: components['schemas']['CurrentLoginResponseDto']
          }
        }
      }
    }
  }
  AuthController_logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 成功响应 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponseDto'] & {
            /** @default null */
            data: null | null
          }
        }
      }
    }
  }
  CommonController_readData: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  CommonController_writeData: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateCommonDto']
      }
    }
    responses: {
      201: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  UserController_pageUser: {
    parameters: {
      query?: {
        /** @description 昵称 */
        nickName?: string
        /** @description 性别代码 */
        gender?: string
        /** @description 性别名称 */
        genderName?: string
        /** @description 生日 */
        birth?: string
        /** @description 手机号 */
        mobile?: string
        /** @description 地址 */
        address?: string
        /** @description 地址详情 */
        addressDetail?: string
        /** @description 婚姻状况代码 */
        maritalStatus?: string
        /** @description 婚姻状况名称 */
        maritalStatusName?: string
        /** @description 邮箱 */
        email?: string
        /** @description 状态：0-禁用，1-启用 */
        status?: string
        /** @description 创建时间 */
        createdAt?: string
        /** @description 修改时间 */
        updatedAt?: string
        /** @description 删除时间 */
        deletedAt?: string
        /** @description 全拼 */
        pinyin?: string
        /** @description 拼音首字母 */
        py?: string
        /** @description 页码 */
        page?: number
        /** @description 每页条数 */
        pageSize?: number
        /** @description 用户名 */
        userName?: string
        /** @description 创建日期开始 */
        createdAtStart?: string
        /** @description 创建日期结束 */
        createdAtEnd?: string
        /** @description 开始 */
        updatedAtStart?: string
        /** @description 结束 */
        updatedAtEnd?: string
        /** @description 排序对象 */
        sort?: {
          [key: string]: string
        }
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 分页成功响应 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponseDto'] & {
            data: components['schemas']['PaginatedResult'] & {
              /**
               * @description 总条数
               * @example 100
               */
              total: number
              /**
               * @description 当前页码
               * @example 1
               */
              page: number
              /**
               * @description 每页条数
               * @example 10
               */
              pageSize: number
              list: components['schemas']['UserPageRespDto'][]
            }
          }
        }
      }
    }
  }
  UserController__pageUser: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UserPageDto']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  UserController_pageOptionUser: {
    parameters: {
      query?: {
        /** @description 页码 */
        page?: number
        /** @description 每页条数 */
        pageSize?: number
        /** @description 关键字 */
        keyword?: string
        /** @description 返回的列表字段 */
        fields?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 分页成功响应 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponseDto'] & {
            data: components['schemas']['PaginatedResult'] & {
              /**
               * @description 总条数
               * @example 100
               */
              total: number
              /**
               * @description 当前页码
               * @example 1
               */
              page: number
              /**
               * @description 每页条数
               * @example 10
               */
              pageSize: number
              list: components['schemas']['UserPageRespDto'][]
            }
          }
        }
      }
    }
  }
  UserController__pageOptionUser: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UserPageOptionDto']
      }
    }
    responses: {
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  UserController_findUserById: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 成功响应 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponseDto'] & {
            data: components['schemas']['UserRespDto']
          }
        }
      }
    }
  }
  UserController_findUserListByIds: {
    parameters: {
      query: {
        /** @description 用“,”拼接的id */
        ids: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 成功响应 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponseDto'] & {
            data: components['schemas']['UserListRespDto']
          }
        }
      }
    }
  }
  UserController_createUser: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UserCreateDto']
      }
    }
    responses: {
      /** @description 成功响应 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponseDto'] & {
            data: components['schemas']['UserRespDto']
          }
        }
      }
    }
  }
  UserController_updateUser: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UserUpdateDto']
      }
    }
    responses: {
      /** @description 成功响应 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponseDto'] & {
            data: components['schemas']['UserRespDto']
          }
        }
      }
    }
  }
  UserController_removeUser: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 成功响应 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponseDto'] & {
            /** @default null */
            data: null | null
          }
        }
      }
    }
  }
  UserController_batchRemoveUser: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['BatchDto']
      }
    }
    responses: {
      /** @description 成功响应 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponseDto'] & {
            data: components['schemas']['BatchRespDto']
          }
        }
      }
    }
  }
  UserController_updateUserStatus: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateStatusDto']
      }
    }
    responses: {
      /** @description 成功响应 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponseDto'] & {
            /** @default null */
            data: null | null
          }
        }
      }
    }
  }
  UserController_batchUpdateUserStatus: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['BatchUpdateStatusDto']
      }
    }
    responses: {
      /** @description 成功响应 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponseDto'] & {
            data: components['schemas']['BatchRespDto']
          }
        }
      }
    }
  }
  UserController_downloadUserTemplate: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 成功响应 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponseDto'] & {
            /** @default null */
            data: null | null
          }
        }
      }
    }
  }
  UserController_importUser: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 成功响应 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponseDto'] & {
            /** @default null */
            data: null | null
          }
        }
      }
    }
  }
  UserController_exportUser: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 成功响应 */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponseDto'] & {
            /** @default null */
            data: null | null
          }
        }
      }
    }
  }
  UserController_checkUnique: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description 成功响应（返回布尔值） */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ApiResponseDto'] & {
            /**
             * @description 校验结果：true 代表通过/唯一，false 代表失败/重复
             * @example true
             */
            data: boolean
          }
        }
      }
    }
  }
}
