export * from '@/modules/file/file.module'
export * from '@/modules/auth/auth.module'
export * from '@/modules/user/user.module'
export * from '@/modules/role/role.module'
export * from '@/modules/shared/shared.module'
export * from '@/modules/value-set/value-set.module'
export * from '@/modules/resource/resource.module'
