## 初始化admin
POST http://localhost:3000/api/auth/init
Content-Type: application/json
x-init-token: cc3cb074-7b53-4ba2-8f96-4d9785c3e5a4

{
  "plainPassword": "Aa111111!"
}


### 登录请求
# @name login
POST http://localhost:3000/api/auth/passwordLogin
Content-Type: application/json
x-req-method: httpClient

{
    "userName": "傅小一",
    "password": "Aa111111!"
}

### 将登录响应头中的 Set-Cookie 保存到变量
@authCookie = {{login.response.headers.Set-Cookie}}


### 查询用户列表
GET http://localhost:3000/api/user/page?userName=test
Content-Type: application/json
Cookie: {{authCookie}}


### 查询用户列表
GET http://localhost:3000/api/user/option?fields=id,userName,mobile
Content-Type: application/json
Cookie: {{authCookie}}

### 根据id查询用户

GET http://localhost:3000/api/user/find/366
Content-Type: application/json
Cookie: {{authCookie}}

### 根据ids查询用户

GET http://localhost:3000/api/user/batch/query?ids=365,366
Content-Type: application/json
Cookie: {{authCookie}}

### 创建用户

POST http://localhost:3000/api/user/create
Content-Type: application/json
Cookie: {{authCookie}}

{
  "userName": "test070106"
}
### 修改用户

POST http://localhost:3000/api/user/update/363
Content-Type: application/json
Cookie: {{authCookie}}

{
  "userName": "test070104"
}

### 删除用户

POST http://localhost:3000/api/user/delete/363
Content-Type: application/json
Cookie: {{authCookie}}


### 批量删除用户

POST http://localhost:3000/api/user/batch/delete
Content-Type: application/json
Cookie: {{authCookie}}

{
  "ids": "368,367"
}

### 修改用户状态

POST http://localhost:3000/api/user/updateStatus/366
Content-Type: application/json
Cookie: {{authCookie}}

{
  "status": "0"
}
### 批量修改用户状态

POST http://localhost:3000/api/user/batch/status
Content-Type: application/json
Cookie: {{authCookie}}

{
  "ids": "365,366",
  "status": "1"
}

### 查询值集

GET http://localhost:3000/api/value-set/page
Content-Type: application/json
Cookie: {{authCookie}}


### 按setCodes查询值集

GET http://localhost:3000/api/value-set/by-set-codes?setCodes=SYS_GENDER,SYS_MARITAL_STATUS
Content-Type: application/json
Cookie: {{authCookie}}

### 批量更新资源顺序

POST http://localhost:3000/api/resource/batchUpdate
Content-Type: application/json
Cookie: {{authCookie}}

{
  "list": [
    {
      "id": 17,
      "sortNumber": 90
    },
    {"label":"test7","uniqueProp":"test7","parentUniqueProp":"noMenuResource","type":"1","notInMenu":"1"}
  ]
}


### 新增时，判断要新增的数据是否为已删除数据，如果是已删除的，则需要复活此数据

POST http://localhost:3000/api/resource/create
Content-Type: application/json
Cookie: {{authCookie}}

{"label":"用户管理","uniqueProp":"user","parentUniqueProp":"","type":"0","notInMenu":"0"}


### 重置密码

POST http://localhost:3000/api/user/resetPassword
Content-Type: application/json
Cookie: {{authCookie}}

{
    "oldPassword": "Owj9l/sEoRZSVPLljiot3B2B2OpG/MSiKFNgKuwcI8MLE2Um+UibObSbYFnWswJoOoUgEqc15/g6xyxF/xaMr2MShBrYNk0SrmIJhKJuRoB7EQs/yWY49bEbdcj+5FHYSbAVcWx/QCa4J/LGdcYTu/0Pgkt8Z9lG5k3LKwgXKhG2QUi7hp7DuAm308B9qOJsVGyrByyFldxOxX8exA+mU9+Lkn+MYl7NCL8BhUgOsSuZyY3GDliGPoFWKgYjqdPoT9nySsbWw7Eg6efsVtPYHEXuDDSy7BxEPsu6tImeUtIzSBiZM1x6dT+HFwkOMzoHJH844pDSUiSnVP9Hg+2FJw==",
    "newPassword": "bCdTukyexH1XNoWT5+jbcN88xfyCa4IJsY4CyzBiWuPu9Xdp/c3KdeNDcAFYcT8FfiVTh0X/X4wA3A1Btp7IanSQSB4o8g3NFFJWv3Ligi+srJ6//FQkioDhWoA4ibvt6Opmm4y10tJdKCC5dIKUHkArwsOYVVbTZsyC4oVLcgAjRciZnf5n6n5NicipIYuismwRucVzTWKPE6qSfCMGDplzi7Cd5B1AqlBZZtQHm0Pjk4mem77ui9FlCvWW0DF8wEYx1mrikByPpbvMUOVxlv2c7wTgIMQmDByONjYt5XQyXe/GJL1JuEea7lGa/aXY+x+ln+6+V2z7u5HP2JyP0Q==",
    "oldPasswordKeyId": "a7a465ea-edad-4f97-becb-288776cc12b0",
    "newPasswordKeyId": "9b9309ef-e021-4357-ac38-d85c6bc5f731",
    "userId": 358
}
